In [1]:
import numpy as np

In [1]:
mylist = [1,2,3,4]

In [2]:
type(mylist)

list

In [3]:
numarray = np.array(mylist) # convert the list to numpy array

In [4]:
numarray

array([1, 2, 3, 4])

In [5]:
type(numarray) # after checking the type it is numpy array

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix) # converts in to rows and columns 3 rows and 1 column

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10) # create the array from start 0 to end 10 but not includes 10

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,10,2) # 3rd parameter is a equaly jumping parameter

array([0, 2, 4, 6, 8])

In [11]:
np.zeros(5) # creates the 0 1d array with 5 times 0 actually you are only passing the colum size and default row size is 1

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((4,5))  # four rows and 5 columns with zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.ones((4,5)) # same as 0

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.linspace(0,10,3) # this function create array evenly space in this example first paramenter is start second is end and 
# 3rd paramters tells 3 times evenly spaced between 0 and 10 

array([ 0.,  5., 10.])

In [18]:
 np.linspace(0,10,42) # 0 to 10 but evenly spaced 42 values

array([ 0.        ,  0.24390244,  0.48780488,  0.73170732,  0.97560976,
        1.2195122 ,  1.46341463,  1.70731707,  1.95121951,  2.19512195,
        2.43902439,  2.68292683,  2.92682927,  3.17073171,  3.41463415,
        3.65853659,  3.90243902,  4.14634146,  4.3902439 ,  4.63414634,
        4.87804878,  5.12195122,  5.36585366,  5.6097561 ,  5.85365854,
        6.09756098,  6.34146341,  6.58536585,  6.82926829,  7.07317073,
        7.31707317,  7.56097561,  7.80487805,  8.04878049,  8.29268293,
        8.53658537,  8.7804878 ,  9.02439024,  9.26829268,  9.51219512,
        9.75609756, 10.        ])

In [19]:
np.eye(5) # to create the identitiy matrix , this takes 1 argument of number of rows and columns why bcz itenbdity matrix 
# have same num of column and rows

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [21]:
np.random.rand(5,6) #create array with 5 rows and 6 columns randomly 

array([[0.89054782, 0.15717564, 0.67971149, 0.13523057, 0.1610514 ,
        0.65340014],
       [0.64112707, 0.114304  , 0.50224192, 0.32070373, 0.7924816 ,
        0.85988652],
       [0.32517309, 0.09499988, 0.0924049 , 0.71313574, 0.62283035,
        0.93914474],
       [0.50668609, 0.20275115, 0.40308709, 0.31615415, 0.09491615,
        0.17441443],
       [0.72115046, 0.36373232, 0.68229205, 0.8104238 , 0.85453595,
        0.77816961]])

In [24]:
np.random.randint(0,100,(5,5)) # random int generate first is start second is end values between these values it will 
# generate the random values and third parameter is matrix size 5 rows and 5 columns

array([[44, 94, 84,  7, 85],
       [14, 50, 25, 82, 93],
       [82, 50, 22,  5, 65],
       [60, 13, 57, 73, 33],
       [72, 58, 27, 83, 70]])

In [27]:
np.random.seed(42)
np.random.rand(4) # if you set the seet any number the rand will generate same values all the times 

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [28]:
arr = np.arange(0,25) 

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.reshape(5,5) # reshape the array 

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
ranarr = np.random.randint(0,101,10)

In [34]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [35]:
ranarr.max()

99

In [36]:
ranarr.min()

2

In [38]:
ranarr.argmax()

5

In [39]:
myarray = np.linspace(0,10,101) # assignment

In [40]:
myarray

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ,
        1.1,  1.2,  1.3,  1.4,  1.5,  1.6,  1.7,  1.8,  1.9,  2. ,  2.1,
        2.2,  2.3,  2.4,  2.5,  2.6,  2.7,  2.8,  2.9,  3. ,  3.1,  3.2,
        3.3,  3.4,  3.5,  3.6,  3.7,  3.8,  3.9,  4. ,  4.1,  4.2,  4.3,
        4.4,  4.5,  4.6,  4.7,  4.8,  4.9,  5. ,  5.1,  5.2,  5.3,  5.4,
        5.5,  5.6,  5.7,  5.8,  5.9,  6. ,  6.1,  6.2,  6.3,  6.4,  6.5,
        6.6,  6.7,  6.8,  6.9,  7. ,  7.1,  7.2,  7.3,  7.4,  7.5,  7.6,
        7.7,  7.8,  7.9,  8. ,  8.1,  8.2,  8.3,  8.4,  8.5,  8.6,  8.7,
        8.8,  8.9,  9. ,  9.1,  9.2,  9.3,  9.4,  9.5,  9.6,  9.7,  9.8,
        9.9, 10. ])

In [41]:
# Lecture 2

In [42]:
arr = np.arange(0,10)

In [43]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [44]:
arr[8]

8

In [45]:
arr[1:8] # getting the elements 1 is starting index and 8 is ending index but not including 8

array([1, 2, 3, 4, 5, 6, 7])

In [46]:
arr[4:]

array([4, 5, 6, 7, 8, 9])

In [47]:
arr[0:5] = 100 # this will assighn 100 a value to all values 0 to 4 index not including 5

In [48]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [54]:
slice_of_arr = arr[0:5] # assigned slice of array from 0 to 5 index

In [55]:
slice_of_arr

array([100, 100, 100, 100, 100])

In [58]:
slice_of_arr[:]= 10 # assign 10 to all the elemets of slice array 

In [57]:
arr # if you notice we have same values of slice_of_arr in arr that means when you assign vcalue to other variables that
# is only refrence value contain not copy of the value whne you cahnge in refrence variable actual arra will be changed as well

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [59]:
arr_copy = arr[0:5].copy() # this is the way of copy  in this case the arr values will be ramain same

In [61]:
arr_copy[:]= 1

In [62]:
arr_copy

array([1, 1, 1, 1, 1])

In [63]:
arr

array([10, 10, 10, 10, 10,  5,  6,  7,  8,  9])

In [2]:
arr_2d = [[10,15,20],[25,30,35],[40,45,50]] # simple python array

In [65]:
arr_2d

[[10, 15, 20], [25, 30, 35], [40, 45, 50]]

In [67]:
arr_2d = np.array(arr_2d) # convert into array of numpy

In [68]:
arr_2d

array([[10, 15, 20],
       [25, 30, 35],
       [40, 45, 50]])

In [70]:
arr_2d.shape

(3, 3)

In [72]:
arr_2d[0][1]

15

In [73]:
arr_2d[0,1] # same as above buit method is different

15

In [12]:
arr_2d[:2][1:] #[1][0]

[[25, 30, 35]]

In [76]:
arr_2d[:2,1:]

array([[15, 20],
       [30, 35]])

In [77]:
arr = np.arange(1,11)# conditional selection 

In [78]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr > 4 # return the array of true if elemnet is greater than 4 else false

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [80]:
bool_arr = arr > 4

In [81]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [82]:
arr[bool_arr] # filters and returns only true vcalues

array([ 5,  6,  7,  8,  9, 10])

In [83]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [84]:
# Assignment 2
# TASK: Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
# NOTE: Many different ways to do this! Your final answer should be an integer.
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/ea3121efac5dd3338c280ff10068f9c8

In [85]:
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

In [89]:
dice_rolls[dice_rolls>2].size

19

# NumPy number 16 video content

In [90]:
arr = np.arange(0,10)

In [91]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
arr + 5 # it will add 5 to each element

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [93]:
arr -2 

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [94]:
arr + arr # this will add each element of array to othe array * keep in mindboth the array size should be same

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [95]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [96]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [97]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [98]:
arr.mean()

4.5

In [99]:
arr.max()

9

In [100]:
arr.min()

0

In [101]:
arr.var()

8.25

In [102]:
arr.std()

2.8722813232690143

In [103]:
arr2d = np.arange(0,25).reshape(5,5)

In [104]:
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [105]:
arr2d.sum()

300

In [107]:
arr2d.sum(axis=0) # this will return 0 colum sum bcz axis is column

array([50, 55, 60, 65, 70])

# Assigment 3 of Numpy

In [108]:
# TASK: Use numpy to check the total remaining in the account after the series of transactions.
# NOTE: Many different ways to do this! 
# MAKE SURE TO READ THE FULL INSTRUCTIONS ABOVE CAREFULLY, AS THE EVALUATION SCRIPT IS VERY STRICT.
# Link to Solution: https://gist.github.com/Pierian-Data/225a449484e12e0535fbbac2231b426b

In [109]:
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])

In [112]:
account_transactions.sum()

2720